### ISSUE TITLE
Проблемы с блоком Попытка/Исключение

### ISSUE THREAD

**Issue by eighth81** [LazarenkoA/Obfuscator-1C#1]
Спасибо за проект. 
Сливает вместе Попытка/Исключение и последующий код. Соответственно в 1С ошибка
Например для кода
&НаСервереБезКонтекста
	Процедура Команда1НаСервере()     
		Попытка		
			Сообщить("Всё хорошо");
		Исключение
			Сообщить("Ошиибка");
		КонецПопытки;			
КонецПроцедуры
На https://play.golang.com/ получаем
ПопыткаСообщить(bмyьrqsi...
ИсключениеСообщить(bмyьrqsiтy...

**Comment by LazarenkoA** [comment]
спасибо, посмотрю

**Comment by LazarenkoA** [comment]
исправил (не надо было отступ задать)
