### ISSUE TITLE
Ошибка обфускации циклов

### ISSUE THREAD

**Issue by ITmind** [LazarenkoA/Obfuscator-1C#2]
При обфускации циклов, в которых есть "продолжить", 1С выдает ошибку.
Пример:

```
инд = 0;
Пока Истина Цикл

	Если инд < 10 Тогда
                инд = инд + 1;
		продолжить;
	КонецЕсли;
        прервать;
КонецЦикла
```

Ошибка:
Оператор Продолжить (Continue) может употребляться только внутри цикла

**Comment by LazarenkoA** [comment]
поправил
